#!/bin/bash

[[ $# == 0 ]] && echo "Usage: $0 <file to watch>" && exit -1

basename=$(basename $1)

while :; do
	
	inotifywait -qe modify $basename.cpp
	clear
	date
	echo
	clang++ -Weverything -std=c++1y -Wno-c++98-compat -o $basename.o $basename.cpp
done
