#!/bin/bash

[[ $# == 0 ]] && echo "Usage: $0 <file to watch>" && exit -1

file=$1

while :; do
	
	inotifywait -qe modify $file
	clear
	date
	echo
	# head -10 tcpdump.txt | node $file
	dd bs=40 count=10 2>/dev/null < /dev/urandom | node $file
done
